# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f37bef7b0df1bc4a962aabfb86904112"
name = "popr-app"
handle = "popr-app"
application_url = "https://millions-evident-promotions-surname.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "popr-test-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://millions-evident-promotions-surname.trycloudflare.com/auth/callback",
  "https://millions-evident-promotions-surname.trycloudflare.com/auth/shopify/callback",
  "https://millions-evident-promotions-surname.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
