name: Pull Request on Branch Push
on:
  push:
    branches-ignore:
      - master
jobs:
  auto-pull-request:
    name: Auto PR for new branch
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "branch_title=Update from $branch" >> $GITHUB_OUTPUT
          label=$(echo $branch | awk -F'/' '{ print $1 }' | head -n 1)
          echo "label=$label" >> $GITHUB_OUTPUT
          issue=$(echo $branch | awk -F'/' '{ print $2 }' | grep -o '[0-9]*' | head -n 1)
          echo "issue=$issue" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Lookup Issue
        id: lookup_issue
        if: ${{ steps.extract_branch.outputs.issue != '' }}
        run: |
          REPO_NAME="${{ github.repository }}"
          ISSUE_NUMBER=${{ steps.extract_branch.outputs.issue }}

          title=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${REPO_NAME}/issues/${ISSUE_NUMBER}" | jq --raw-output '.title')
          echo "title=$title" >> $GITHUB_OUTPUT
          fixes="Fixes #${{ steps.extract_branch.outputs.issue }}"
          echo "fixes=$fixes" >> $GITHUB_OUTPUT
      - name: Add ticket label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.extract_branch.outputs.label != '' && steps.extract_branch.outputs.issue != '' }}
        with:
          number: ${{ steps.extract_branch.outputs.issue }}
          labels: ${{ steps.extract_branch.outputs.label }}
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        id: pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_TITLE: ${{ steps.lookup_issue.outputs.title || steps.extract_branch.outputs.branch_title }}
          PULL_REQUEST_BODY: |
            This is an automated pull request to update from branch ${{ steps.extract_branch.outputs.branch }}

            ${{ steps.lookup_issue.outputs.fixes || '' }}
      - name: Add PR label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.pull_request.outputs.pull_request_number != '' }}
        with:
          number: ${{ steps.pull_request.outputs.pull_request_number }}
          labels: WIP
